language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - 'pip install pyzmq --install-option="--zmq=bundled"'
  - "pip install -r requirements.txt"
# command to run tests
script: nosetests --exe
